title: "Infrastruktura IT"
title_meta: "Your devops assistant"
company_info: |
  Infrastruktura.IT RAFAŁ MASIAREK
  VAT EU: (PL)7272780694
  Olimp**ska 4/19
  94-043 LDZ, PL

baseurl: "/"
url: "https://infrastruktura.it"

github_url: https://github.com/Infrastrukturait/
status_url: https://status.infrastruktura.it/

plugins:
  - jekyll-feed
