title: "Infrastruktura IT"
title_meta: "Your devops assistant"
company_info: |
  Infrastruktura.IT RAFAŁ MASIAREK
  VAT EU: (PL)7272780694

baseurl: "/"
url: "https://infrastruktura.it"

github_url: https://github.com/Infrastrukturait/
status_url: https://status.infrastruktura.it/

links:
  - github :
    url: "https://github.com/Infrastrukturait/"
    icon: "fab fa-github"
    public : true
  - status:
    url: "https://status.infrastruktura.it/"
    icon: "fab fa-watchman-monitoring"
    public: false

plugins:
  - jekyll-feed
